project:
  type: website
  resources:
    - project-matchmaker/**
    - project-matchmaker/*
    - project-matchmaker/student_data.json
    - demos/p1-music/**

website:
  title: "ECE4424/CS4824: Machine Learning"
  description: "Learn ML by Building - Fall 2025"
  site-url: https://jinming99.github.io/learn-ml-by-building/
  repo-url: https://github.com/jinming99/learn-ml-by-building
  repo-actions: []
  
  navbar:
    background: primary
    foreground: light
    left:
      - text: "Home"
        href: index.qmd
      - text: "Schedule"
        href: schedule.qmd
      - text: "Projects"
        href: projects/project1.qmd
      - text: "Resources"
        href: resources.qmd
      - text: "Project Matchmaker"
        href: project-matchmaker/
    right:
      - icon: github
        href: https://github.com/jinming99/learn-ml-by-building
      - text: "Piazza"
        href: https://piazza.com/class/melrw2iqdro2ar/
      - text: "Canvas"
        href: https://canvas.vt.edu/
  
  sidebar:
    style: "floating"
    collapse-level: 2
    contents:
      - section: "Course Info"
        contents:
          - text: "Syllabus"
            href: syllabus.qmd
          - text: "Schedule"
            href: schedule.qmd
      
      - section: "Module 1: Let's Predict"
        contents:
          - text: "L0: Environment Setup"
            href: lectures/00-setup.qmd
          - text: "L1: Welcome to ML"
            href: lectures/01-overview.qmd
          - text: "L2: k-NN"
            href: lectures/02-knn.qmd
          - text: "L3: Linear Regression"
            href: lectures/03-linear.qmd
          - text: "L4: Gradient Descent and Optimization"
            href: lectures/04-optimization.qmd
          - text: "L5: Probabilistic Classification"
            href: lectures/05-probclass.qmd
          - text: "L6: Decision Trees (Coming Soon)"
            href: "#"
      
      - section: "Module 2: Let's Understand"
        contents:
          - text: "L7-11: Coming Soon"
            href: "#"
      
      - section: "Module 3: Let's Discover"
        contents:
          - text: "L12-13: Coming Soon"
            href: "#"
      
      - section: "Module 4: Let's See & Chat"
        contents:
          - text: "L14-20: Coming Soon"
            href: "#"
      
      - section: "Module 5: Let's Act"
        contents:
          - text: "L21-23: Coming Soon"
            href: "#"
      
      - section: "Module 6: Let's Impact"
        contents:
          - text: "L24-25: Coming Soon"
            href: "#"
      
      - section: "Projects"
        contents:
          - text: "Project 1: KNN Music Recommender"
            href: projects/project1.qmd
          - text: "Project 2-3: Coming Soon"
            href: "#"

format:
  html:
    theme: morph
    # css: styles.css
    toc: true
    toc-depth: 2